In [ ]:
# Examples and images from tensors.net

In [47]:
import numpy as np

## Tensor contraction with Numpy

![Contraction](imgs/contraction.png)


In [46]:
d = 10
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)

![Contraction steps](imgs/contraction-steps.png)

In [39]:
#1. Permute the A and B tensors such that the indices to be contracted becoming
# the trailing and leading indices respectively (with conssitent order between
# both tensors)
Ap = A.transpose(0,2,1,3)
Bp = B.transpose(0,3,1,2)

In [40]:
#2. Reshape tensors into matrices (between indices to be contracted versus the remaining indices)
App = Ap.reshape(d**2,d**2)
Bpp = Bp.reshape(d**2,d**2)

In [41]:
#3. Do the matrix multiplication
Cpp = App @ Bpp

In [43]:
#4. Reshape C back into a tensor, perform final permutation if desired index ordering is different from current
C = Cpp.reshape(d,d,d,d)

## Tensor decomposition

In [10]:
from numpy import linalg as LA
from ncon import ncon # Library from https://github.com/mhauru/ncon

In [27]:
##### Ex2.2(a): SVD of matrix
d1 = 10
d2 = 6

A = np.random.rand(d1,d2)

[U,S,Vh] = LA.svd(A, full_matrices=False)

# check result
Af = U @ np.diag(S) @ Vh
dA = LA.norm(Af-A) 

print("A shape: {}".format(A.shape))
print("Af shape: {}".format(Af.shape))
print(dA)
print(A - Af)

A shape: (10, 6)
Af shape: (10, 6)
1.5860799769742405e-15
[[-9.71445147e-17 -4.44089210e-16 -5.55111512e-17  0.00000000e+00
   8.32667268e-17 -2.22044605e-16]
 [ 1.11022302e-16  2.22044605e-16 -1.66533454e-16 -1.11022302e-16
  -3.33066907e-16 -1.11022302e-16]
 [ 0.00000000e+00  3.33066907e-16 -3.33066907e-16 -2.22044605e-16
  -5.55111512e-16  0.00000000e+00]
 [ 5.55111512e-17  1.11022302e-16 -5.55111512e-17 -2.22044605e-16
   0.00000000e+00 -1.11022302e-16]
 [-2.22044605e-16  5.55111512e-17 -5.55111512e-17 -8.32667268e-17
  -2.77555756e-16 -2.22044605e-16]
 [-2.22044605e-16 -1.11022302e-16  0.00000000e+00 -1.11022302e-16
  -2.22044605e-16  0.00000000e+00]
 [-2.22044605e-16 -1.80411242e-16 -5.55111512e-17 -2.22044605e-16
  -3.33066907e-16 -2.77555756e-16]
 [-2.22044605e-16 -5.55111512e-17 -1.94289029e-16 -1.11022302e-16
  -3.33066907e-16 -2.77555756e-16]
 [-2.22044605e-16  3.33066907e-16  0.00000000e+00 -1.11022302e-16
  -2.77555756e-17 -1.11022302e-16]
 [-1.11022302e-16  0.00000000e+00

In [14]:
print(U)
print(S)
print(Vh)

[[-0.30541239 -0.2300157   0.09856029 -0.64787275  0.01118035 -0.28015183]
 [-0.39103982  0.33270347 -0.17517714  0.37845727  0.140369   -0.12910614]
 [-0.34632264  0.31499202 -0.09560308 -0.24862163  0.40621092  0.4041008 ]
 [-0.31582716 -0.22205691  0.48251923  0.00747775 -0.18112083 -0.16443598]
 [-0.23957282 -0.5963247  -0.1343162  -0.09733224  0.28377994  0.38596452]
 [-0.31882471  0.37959043  0.27098677 -0.07954835 -0.19582966  0.44111291]
 [-0.36113287  0.16488662 -0.54245984 -0.20542716 -0.19986361 -0.43575981]
 [-0.24533948 -0.14673795  0.16575799  0.39559935  0.59110667 -0.32846245]
 [-0.29283065  0.0533428   0.43412326  0.14242944 -0.27162401 -0.09228291]
 [-0.31420126 -0.36961441 -0.34052609  0.37466726 -0.44760139  0.25430368]]
[4.00505739 1.50239398 1.05738004 0.89881046 0.83198137 0.22823822]
[[-0.38497975 -0.31652608 -0.45455215 -0.44256714 -0.44806245 -0.3851734 ]
 [ 0.34161223 -0.62263931 -0.55231895  0.20378486  0.32098259  0.21449255]
 [ 0.70798844 -0.23972397  0.36

## MPS